<a href="https://colab.research.google.com/github/HinaNitano/EU_M_Math/blob/main/Chap05_Ex_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import scipy as sp

In [ ]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

# 特異値分解の関数linalg.svd
U, s, Vs = sp.linalg.svd(B)
m, n = B.shape

S = sp.linalg.diagsvd(s,m,n)

print('U.S.V* = \n', U@S@Vs)

U.S.V* = 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
