<a href="https://colab.research.google.com/github/HinaNitano/EU_M_Math/blob/main/Chap05_Ex_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import scipy as sp

In [ ]:
A = A = np.identity(3)
print(A)
A[0,:]=1
A[:,0]=1
A[0,0]=3
b = np.ones(3)
print(A)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
[1. 1. 1.]


In [ ]:
(LU,piv) = sp.linalg.lu_factor(A)

L = np.identity(3) + np.tril(LU,-1)
U = np.triu(LU)
P = np.identity(3)[piv]

x = sp.linalg.lu_solve((LU,piv),b)
x

array([-1.,  2.,  2.])