<a href="https://colab.research.google.com/github/HinaNitano/EU_M_Math/blob/main/Chap05_Hw_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 以下のライブラリを使う
import numpy as np
import numpy.random as random
import scipy as np

# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

# 小数第３位まで
%precision 3

'%.3f'

In [ ]:
sample_array = np.arange(10)
print('sample_array:', sample_array)

sample_array: [0 1 2 3 4 5 6 7 8 9]


<ipython-input-2-dd04b9cbe345>:1: DeprecationWarning: scipy.arange is deprecated and will be removed in SciPy 2.0.0, use numpy.arange instead
  sample_array = np.arange(10)


In [ ]:
# 元のデータ
print(sample_array)

# 前から数字を５つ取得して、sample_array_sliceに入れる
sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [ ]:
# sample_array_sliceの３文字目までは、10で置換
sample_array_slice[0:3] = 10
print(sample_array_slice)

# スライスの変更はオリジナルリストも変更
print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [ ]:
# copyして別のobjectを作成
sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)

# 元のリストは変更されてない
print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


<ipython-input-5-3485650d6071>:2: DeprecationWarning: scipy.copy is deprecated and will be removed in SciPy 2.0.0, use numpy.copy instead
  sample_array_copy = np.copy(sample_array)


In [ ]:
# データの準備
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


<ipython-input-6-d6d28e32173d>:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  sample_names = np.array(['a', 'b', 'c', 'd', 'a'])


In [ ]:
sample_names == 'a'

array([ True, False, False, False,  True])

In [ ]:
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [ ]:
# 条件制御のためのプール配列を作成
cond_data = np.array([True, True, False, False, True])

# 配列 x_arrayを作成
x_array = np.array([1,2,3,4,5])

# 配列y_arrayを作成
y_array = np.array([100, 200, 300, 400, 500])

# 条件制御実施
print(np.where(cond_data,x_array,y_array))

[  1   2 300 400   5]


<ipython-input-9-0c236a15ee65>:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  cond_data = np.array([True, True, False, False, True])
<ipython-input-9-0c236a15ee65>:5: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  x_array = np.array([1,2,3,4,5])
<ipython-input-9-0c236a15ee65>:8: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  y_array = np.array([100, 200, 300, 400, 500])
<ipython-input-9-0c236a15ee65>:11: DeprecationWarning: scipy.where is deprecated and will be removed in SciPy 2.0.0, use numpy.where instead
  print(np.where(cond_data,x_array,y_array))


In [ ]:
cond_data = np.array([True, True, False, False, True])
print(cond_data)

# 重複削除
print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


<ipython-input-10-f969fe25896b>:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  cond_data = np.array([True, True, False, False, True])
<ipython-input-10-f969fe25896b>:5: DeprecationWarning: scipy.unique is deprecated and will be removed in SciPy 2.0.0, use numpy.unique instead
  print(np.unique(cond_data))


In [ ]:
# ユニバーサル関数
sample_data = np.arange(10)
print('元のデータ:', sample_data)
print('すべての要素の平方根:', np.sqrt(sample_data))
print('すべての要素のネイピア指数関数:', np.exp(sample_data))

元のデータ: [0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根: [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイピア指数関数: [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


<ipython-input-11-47b94205e523>:2: DeprecationWarning: scipy.arange is deprecated and will be removed in SciPy 2.0.0, use numpy.arange instead
  sample_data = np.arange(10)
<ipython-input-11-47b94205e523>:4: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  print('すべての要素の平方根:', np.sqrt(sample_data))
<ipython-input-11-47b94205e523>:5: DeprecationWarning: scipy.exp is deprecated and will be removed in SciPy 2.0.0, use numpy.exp instead
  print('すべての要素のネイピア指数関数:', np.exp(sample_data))


In [ ]:
# arangeで9つの要素を持つ配列を生成。reshapeで3行3列の行列に再形成
sample_multi_array_data1 = np.arange(9).reshape(3,3)

print(sample_multi_array_data1)

print('最小値:', sample_multi_array_data1.min())
print('最大値:', sample_multi_array_data1.max())
print('平均:', sample_multi_array_data1.mean())
print('合計:', sample_multi_array_data1.sum())

# 行列を指定して合計値を求める
print('行の合計:', sample_multi_array_data1.sum(axis=1))
print('列の合計:', sample_multi_array_data1.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値: 0
最大値: 8
平均: 4.0
合計: 36
行の合計: [ 3 12 21]
列の合計: [ 9 12 15]


<ipython-input-14-961d31f9161a>:2: DeprecationWarning: scipy.arange is deprecated and will be removed in SciPy 2.0.0, use numpy.arange instead
  sample_multi_array_data1 = np.arange(9).reshape(3,3)


In [ ]:
# 真偽値の配列関数
cond_data = np.array([True, True, False, False, True])

print('Trueがすくなくとも1つあるかどうか:', cond_data.any())
print('すべてTrueかどうか:', cond_data.all())

Trueがすくなくとも1つあるかどうか: True
すべてTrueかどうか: False


<ipython-input-13-312dae2604d9>:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  cond_data = np.array([True, True, False, False, True])


In [ ]:
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)
print('5より大きい数字がいくつあるか:',(sample_multi_array_data1>5).sum())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5より大きい数字がいくつあるか: 3


<ipython-input-16-805eaabe5472>:1: DeprecationWarning: scipy.arange is deprecated and will be removed in SciPy 2.0.0, use numpy.arange instead
  sample_multi_array_data1 = np.arange(9).reshape(3,3)


In [ ]:
# 行列計算
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('対角成分:', np.diag(sample_multi_array_data1))
print('対角成分の和:', np.trace(sample_multi_array_data1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
対角成分: [0 4 8]
対角成分の和: 12


<ipython-input-17-ac85de55aba1>:2: DeprecationWarning: scipy.arange is deprecated and will be removed in SciPy 2.0.0, use numpy.arange instead
  sample_multi_array_data1 = np.arange(9).reshape(3,3)
<ipython-input-17-ac85de55aba1>:5: DeprecationWarning: scipy.diag is deprecated and will be removed in SciPy 2.0.0, use numpy.diag instead
  print('対角成分:', np.diag(sample_multi_array_data1))
<ipython-input-17-ac85de55aba1>:6: DeprecationWarning: scipy.trace is deprecated and will be removed in SciPy 2.0.0, use numpy.trace instead
  print('対角成分の和:', np.trace(sample_multi_array_data1))


In [ ]:
# データの準備
sample_array = np.arange(10)
sample_array

<ipython-input-18-d1ec07251158>:2: DeprecationWarning: scipy.arange is deprecated and will be removed in SciPy 2.0.0, use numpy.arange instead
  sample_array = np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 再形成
sample_array2 = sample_array.reshape(2,5)
sample_array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
sample_array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# データの準備
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
print(sample_array3)
print(sample_array4)

# 行方向に結合。パラメータのaxisに0を指定
np.concatenate([sample_array3, sample_array4],axis=0)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


<ipython-input-22-6a7aac7809ac>:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  sample_array3 = np.array([[1,2,3],[4,5,6]])
<ipython-input-22-6a7aac7809ac>:3: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  sample_array4 = np.array([[7,8,9],[10,11,12]])
<ipython-input-22-6a7aac7809ac>:8: DeprecationWarning: scipy.concatenate is deprecated and will be removed in SciPy 2.0.0, use numpy.concatenate instead
  np.concatenate([sample_array3, sample_array4],axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# vstackを使った行方向結合の方法
np.vstack((sample_array3, sample_array4))

<ipython-input-23-01761a68b9ef>:2: DeprecationWarning: scipy.vstack is deprecated and will be removed in SciPy 2.0.0, use numpy.vstack instead
  np.vstack((sample_array3, sample_array4))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# 列方向に結合
np.concatenate([sample_array3, sample_array4],axis=1)

<ipython-input-24-68a9d54ae9aa>:2: DeprecationWarning: scipy.concatenate is deprecated and will be removed in SciPy 2.0.0, use numpy.concatenate instead
  np.concatenate([sample_array3, sample_array4],axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
# 列方向結合の他の方法
np.hstack((sample_array3, sample_array4))

<ipython-input-25-46670b4d0d54>:2: DeprecationWarning: scipy.hstack is deprecated and will be removed in SciPy 2.0.0, use numpy.hstack instead
  np.hstack((sample_array3, sample_array4))


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
# データの用意
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
sample_array_vstack = np.vstack((sample_array3, sample_array4))
sample_array_vstack

<ipython-input-26-31bc50133767>:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  sample_array3 = np.array([[1,2,3],[4,5,6]])
<ipython-input-26-31bc50133767>:3: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  sample_array4 = np.array([[7,8,9],[10,11,12]])
<ipython-input-26-31bc50133767>:4: DeprecationWarning: scipy.vstack is deprecated and will be removed in SciPy 2.0.0, use numpy.vstack instead
  sample_array_vstack = np.vstack((sample_array3, sample_array4))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
first,second,third = np.split(sample_array_vstack,[1,3])
print(first)

[[1 2 3]]


<ipython-input-27-d3188fc1a1c4>:1: DeprecationWarning: scipy.split is deprecated and will be removed in SciPy 2.0.0, use numpy.split instead
  first,second,third = np.split(sample_array_vstack,[1,3])


In [ ]:
print(second)

[[4 5 6]
 [7 8 9]]


In [ ]:
second[0]

array([4, 5, 6])

In [ ]:
print(third)

[[10 11 12]]


In [ ]:
# データの用意
sample_array5 = np.array([[13,14,15],[16,17,18],[19,20,21]])
sample_array_vstack2 = np.vstack((sample_array3, sample_array4, sample_array5))

print(sample_array_vstack2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


<ipython-input-31-ba16806e7fdf>:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  sample_array5 = np.array([[13,14,15],[16,17,18],[19,20,21]])
<ipython-input-31-ba16806e7fdf>:3: DeprecationWarning: scipy.vstack is deprecated and will be removed in SciPy 2.0.0, use numpy.vstack instead
  sample_array_vstack2 = np.vstack((sample_array3, sample_array4, sample_array5))


In [ ]:
first,second,third,fourth = np.split(sample_array_vstack2,[2,3,5])
print('・1つ目:\n', first,'\n')
print('・2つ目:\n', second,'\n')
print('・3つ目:\n', third,'\n')
print('・4つ目:\n', fourth,'\n')

・1つ目:
 [[1 2 3]
 [4 5 6]] 

・2つ目:
 [[7 8 9]] 

・3つ目:
 [[10 11 12]
 [13 14 15]] 

・4つ目:
 [[16 17 18]
 [19 20 21]] 



<ipython-input-32-b36db6492705>:1: DeprecationWarning: scipy.split is deprecated and will be removed in SciPy 2.0.0, use numpy.split instead
  first,second,third,fourth = np.split(sample_array_vstack2,[2,3,5])


In [ ]:
first[0]

array([1, 2, 3])

In [ ]:
first[1]

array([4, 5, 6])

In [ ]:
# repeatを使うと、各要素が指定した回数だけ繰り返されて生成される
first.repeat(5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6])

In [ ]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


<ipython-input-36-572f1d4a6026>:1: DeprecationWarning: scipy.arange is deprecated and will be removed in SciPy 2.0.0, use numpy.arange instead
  sample_array = np.arange(10)


In [ ]:
sample_array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])